mystr = "Gaurav is a coder"
# print(len(mystr))
# print(mystr[-1:6])
print(mystr.replace("is", "an"))
print(mystr.find("v"))
print(mystr.endswith("r"))
print(mystr.index("i"))
print(mystr.count("a"))
print(mystr.split())
print(mystr.capitalize())
print(mystr.lower())
print(mystr.upper())