<<<<<<< HEAD
f = open("gaurav.txt")
f.seek(10)
print(f.tell())
print(f.readline())
# print(f.tell())
print(f.readline())
# print(f.tell())
=======
f = open("gaurav.txt")
f.seek(10)
print(f.tell())
print(f.readline())
# print(f.tell())
print(f.readline())
# print(f.tell())
>>>>>>> 8ad8ee1 (Add initial files)
f.close()